### ISSUE TITLE
Not able to run on miq master branch

### ISSUE THREAD

**Issue by tjyang** [ramrexx/ServiceNow_CMDB#1] opened 2017-07-31 22:22 UTC
Hi

I am able to run this on fine-2 instance but when I try this on master branch(07/31/2017).
I got following error.

```
[root@miq02 ~]# /usr/bin/miqimport buttons /root/ServiceNow_CMDB/buttons/ServiceNow_CMDB_Vm_.yaml
/var/www/miq/vmdb ~
Button Class: [Vm]
        Button Group: [ServiceNow_CMDB]
                Adding Button: Update CMDB Record
rake aborted!
ActiveModel::MissingAttributeError: can't write unknown attribute `applies_to_exp`
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:146:in `block in import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:121:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:121:in `import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:184:in `block in import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:172:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:172:in `import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:63:in `block in import_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:62:in `import_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:9:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:269:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:buttons:import
(See full trace by running task with --trace)
~
[root@miq02 ~]#

```

**Comment by ramrexx** [comment] 2017-08-01 02:47
I have never tested this on the master branch. What happens if you export an existing button from master? What does the yml file look like? Specifically what does the `applies_to_exp` section in the yml look like?

**Comment by easyljy** [comment] 2017-08-01 22:02
It works to export an existing button, but the yml looks different. applies_to_exp doesn't exist.

---
:custom_buttons_sets:
- name: eee|Vm|
  description: eeee
  set_type: CustomButtonSet
  read_only:
  mode:
  custom_buttons:
  - description: test button
    applies_to_class: Vm
    options:
      :button_icon: noicon
      :display: true
      :open_url: false
      :display_for: single
      :submit_how: one
    userid: demo
    wait_for_complete:
    name: test button
    visibility:
      :roles:
      - _ALL_
    applies_to_id:
    resource_actions:
      action:
      ae_namespace: SYSTEM
      ae_class: PROCESS
      ae_instance: Request
      ae_message:
      ae_attributes:
        request: test_invalid
  set_data:
    :button_order:
    - test button
    :button_icon: ffff
    :display: true
    :group_index: 1

**Comment by ramrexx** [comment] 2017-08-02 02:59
So try removing the applies_to_exp from the yml and try the import again.

**Comment by ramrexx** [comment] 2017-08-02 17:14
Did that work?

**Comment by tjyang** [comment] 2017-08-02 17:31
I removed 3 occurrences of "applies_to_exp" in ServiceNow_CMDB_Vm_.yaml.
Still getting same error message.

```
[root@miq02 ~]# /usr/bin/miqimport  buttons /root/ServiceNow_CMDB/buttons/ServiceNow_CMDB_Vm_.yaml
/var/www/miq/vmdb ~
Button Class: [Vm]
        Button Group: [ServiceNow_CMDB]
                Adding Button: Update CMDB Record
rake aborted!
ActiveModel::MissingAttributeError: can't write unknown attribute `applies_to_exp`
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:146:in `block in import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:121:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:121:in `import_custom_buttons'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:184:in `block in import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:172:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:172:in `import_custom_button_sets'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:63:in `block in import_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:62:in `import_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:9:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:269:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:buttons:import
(See full trace by running task with --trace)
~
[root@miq02 ~]# grep  applies_to_exp /root/ServiceNow_CMDB/buttons/ServiceNow_CMDB_Vm_.yaml
[root@va32lmiq02 ~]# date
Wed Aug  2 13:30:21 EDT 2017
[root@miq02 ~]#

```

**Comment by ramrexx** [comment] 2017-08-02 17:35
Since you are running on master and not CloudForms i am not sure i will be able to help. Except that the issue is probably related to the import utilities. I would open an issue with https://github.com/rhtconsulting/cfme-rhconsulting-scripts. Since they are the author of the import scripts.

Closing issue.

**Closed as completed by ramrexx** 2017-08-02 17:35 UTC

**Comment by easyljy** [comment] 2017-08-02 17:38
FYI, comment out below line and I can import the buttons.

/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake
    146           #custom_button['applies_to_exp'] = cb['applies_to_exp']

**Comment by tjyang** [comment] 2017-08-02 18:05
Thanks for the help @ramrexx and @easyljy.
